flyteorg/flytestdlib

- Gopkg.lock
- utils/auto_refresh_cache.go
- utils/auto_refresh_cache_test.go
- utils/auto_refresh_example_test.go
This changes the backing data store behind the AutoRefreshCache which some of the Flyte engine plugins use from a `sync.Map` to an [LRU cache](https://github.com/hashicorp/golang-lru) (released under Mozilla Public License 2.0).
* If supplied with a Prometheus metrics scope, a counter will be created for evictions.  The rate at which counter increases can be used to gauge how poorly the cache is performing - if the rate of evictions is ~ the rate of GetOrCreate calls then something is amiss.
* Heavily modified the unit test, but they're still only cursory.  Open to suggestions on how to do more testing.
> Use an LRU in AutoRefreshCache

- logger/logger.go
Flink operator uses https://github.com/go-resty/resty to communicate to Job manager. Resty call logs do not follow the logger settings.
If flytestdlib logger can expose writer, I can pass it in to resty.SetLogger(..)
Alternatively we can expose GetLogger if you think that is better.
> Flinkk8soperator needs Log writer to be passed to Resty

- promutils/workqueue.go
Interface workqueue.MetricsProvider has backward incompatible interface in the newer versions of Client Go. 
Until we permanently upgrade Flytestdlib to the new interface, a temp fix to make Flytestdlib work with newer versions of client-go
> Set provider only if all methods are implemented

- contextutils/context.go
- contextutils/context_test.go
- promutils/labeled/counter_test.go
- promutils/labeled/keys.go
- promutils/labeled/keys_test.go
- promutils/labeled/stopwatch_test.go
- storage/cached_rawstore_test.go
- utils/marshal_utils_test.go
In building alarms and graphs on executions, it is not currently possible to different between executions started by different launch plans.  This is problematic for us in our functional tests because the launch plan ID is what differentiates beta and prod executions.  Likewise, this would make it difficult/impossible for users to alert on parameterized scheduled workflows.
This adds the necessary label context utils which will be used to set the launch plan context by Propeller.
> Add lp as an optional label for stats

- boilerplate/lyft/golang_test_targets/Makefile
- go.sum
workaround https://github.com/golang/go/issues/30515
> Fix go module change

- contextutils/context.go
- promutils/labeled/counter.go
- promutils/labeled/metric_option.go
- promutils/labeled/stopwatch.go
- storage/stow_store.go
- storage/utils.go
Adds failure type as a tag on head, read and write failures emitted by storage package.
Added support in labeled package for adding additional labels on metrics then used that in storage package.
https://github.com/lyft/flyte/issues/216
_NA_
> Add a failure type label to failure metrics in storage package

- promutils/labeled/counter.go
- promutils/labeled/gauge.go
- promutils/labeled/gauge_test.go
- promutils/labeled/stopwatch.go
Some of the labeled metrics forgot to add the additional labels.
In all the places where we call GetMetricWith, we now pass the additional labels.
NA
NA
> Add additional labels if present

- config/regexp.go
- config/regexp_test.go
- internal/utils/parsers.go
- internal/utils/parsers_test.go
Provide `regexp` config type so user can do for example:
```
...
filter    config.Regexp
...
```
As commented https://github.com/lyft/flytepropeller/pull/90#discussion_r393109951, it is better to have an dedicated `regexp` config type so validation can be done properly and early on.
https://github.com/lyft/flytepropeller/pull/90 Might not be needed after all, but having such a type may still make sense.
NA
NA
> support regexp config

- storage/stow_store.go
There is a missing parameter when logging, so container name is not logged.
This is a minor fix that doesn't require design.
> Fix container name logging

- storage/stow_store.go
- storage/stow_store_test.go
Signed-off-by: Katrina Rogan <katrogan9@gmail.com>
Stow [v0.2.6](https://github.com/graymeta/stow/releases/tag/v0.2.6) changes stow s3 location Container behavior [to elide container lookup](https://github.com/graymeta/stow/commit/0862eee499c9e7b87763e9f30af7b99479177ec5#diff-dd65194c93a22b03112f6701be7b9ad784706bdb374cc5b2d9f8ffe56b480564R174) when a region is set.
Discovered while upgrading flyteadmin and integration tests broke
https://github.com/flyteorg/flyte/issues/815
_NA_
> Always try to create a bucket when loading a container

- config/tests/accessor_test.go
- config/tests/testdata/array_config_2.yaml
- config/tests/types_test.go
- config/viper/viper.go
The default behavior for the mapstructure package used to merge new and default configs is to merge maps by setting all keys and to merge arrays by replacing the first n elements with the new n elements while leaving the rest intact.
The intuitive behavior, talking to users, is that when a field is set in a config, it completely replaces the default config.
There is a ZeroFields setting to be set in the decoder used. It only zeros fields that are being replaced from the config file and not just all fields...
https://github.com/flyteorg/flyte/issues/948
> Zero fields overriden in config files to avoid undesired merging logic

- config/tests/accessor_test.go
- config/tests/testdata/map_config.yaml
- config/tests/testdata/map_config_nested.yaml
- config/tests/types_test.go
- config/viper/viper.go
viper, by design, doesn't support [case sensitive keys](https://github.com/spf13/viper#does-viper-support-case-sensitive-keys) and that ends up lower casing all keys regardless of whether the target field is a map. Flyte config has been using a workaround where we set the config values (e.g. in yaml files) for maps as yaml arrays instead to preserve their case sensitivity. After [this change](https://github.com/flyteorg/flytestdlib/pull/81) that sets ZeroFields to true, the logic in mapstructure package breaks when doing the slice to map conversion. This PR adds an additional hook that does the conversion.
https://github.com/flyteorg/flyte/issues/948
> Fix zeroFields setting when merging slices into maps

- config/tests/testdata/config.yaml
- config/tests/types_test.go
- config/viper/viper.go
- config/viper/viper_test.go
Support converting string config values to []byte config fields.
> config: Support converting string configs to []byte

- config/viper/viper.go
- Fixed logger level in viper package 
https://github.com/flyteorg/flyte/issues/<number>
_NA_
OR
> Fixed logger levels in viper

- go.mod
- go.sum
- utils/marshal_utils.go
- utils/marshal_utils_test.go
Signed-off-by: Katrina Rogan <katroganGH@gmail.com>
Add UnmarshalStructToObj to marshal utils
https://github.com/flyteorg/flyte/issues/998
_NA_
> Add UnmarshalStructToObj to marshal utils

- config/tests/accessor_test.go
- config/tests/testdata/bad_config.yaml
- config/viper/viper.go
Update `strictMode` to capture existing flags in a flagset before parsing params. This way it can avoid failing when there are flags defined outside of stdlibConfig world.
fixes https://github.com/flyteorg/flyte/issues/1209
> stdlibConfig strictMode should not fail if there are existing flags

- storage/config.go
- storage/stow_store.go
- storage/stow_store_test.go
Context :- A user started [discussion](https://github.com/flyteorg/flyte/discussions/1287) regarding a bug in copiliot.  where copiliot failes with large files because of stdlib limit check.  We don't want any limit on size in case of copiliot
- If GetLimitMegabytes is 0 then  don't check size limit 
fixes https://github.com/flyteorg/flyte/issues/1251
https://github.com/flyteorg/flyte/issues/1253
https://github.com/flyteorg/flyte/discussions/1287
_NA_
OR
> Added default no limit on storage 

- cli/pflags/api/testdata/testtype.go
- cli/pflags/api/testdata/testtype_test.go
- storage/config.go
- storage/config_flags.go
- storage/config_flags_test.go
- storage/stow_store.go
- storage/stow_store_test.go
Currently we are not generating pflag for stow config that means we are only able to pass sandbox storage config via flags.
- Added pflag for stow config
```bash
$  --stow.kind S3 --stow.config key=value,key2=val2
```
_NA_
OR
> Added pflag for stow config in storage

- storage/stow_store.go
```bash
Is not working as expected 
if  !reflect.DeepEqual(cfg.Stow, StowConfig{}) {
}
```
```bash
if  len(cfg.Stow.Kind) > 0 && len(cfg.Stow.Config) > 0  {
}
```
_NA_
OR
> hotfix for stow config

- cache/auto_refresh.go
- cache/sync_set.go
- cache/sync_set_test.go
Support DeleteDelayed operation in AutoRefresh cache. This allows callers to safely enqueue a delete operation for a key and ensure it gets deleted even if the cache is in the middle of being refreshed.
https://github.com/flyteorg/flyte/issues/1379
> Support DeleteDelayed operation in AutoRefresh cache

- .github/workflows/pull_request.yml
- cache/mocks/AutoRefresh.go
- logger/config_flags.go
- logger/config_flags_test.go
Missed running `go generate ./...` after updating the AutoRefresh cache interface. Added a github workflow to check for that for future changes.
https://github.com/flyteorg/flyte/issues/1379
> Go Generate and Add a Workflow to perform a sanity check

- config/config_cmd.go
Signed-off-by: Kevin Su <pingsutw@apache.org>
Print subsection in different heading level
Before:
After:
docs: https://flyte--1608.org.readthedocs.build/en/1608/deployment/cluster_config/flyteadmin_config.html#grpcauthorizationheader-string
rst heading format: https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#headings
Related to https://github.com/flyteorg/flyte/pull/1608
_NA_
> Print subsection in different heading level

- promutils/labeled/counter.go
- promutils/labeled/gauge.go
- promutils/labeled/stopwatch.go
- promutils/labeled/summary.go
- promutils/labeled/summary_test.go
Add labeled Prometheus Summary (missing type)
Duplicate of https://github.com/flyteorg/flytestdlib/pull/109 (since it lacked permissions)
- [ x ] Feature
`promutils` does not offer the `labeled` alternative for `prometheus.Summary`
_NA_
_NA_
> Add labeled Prometheus summary

- promutils/labeled/counter.go
- promutils/labeled/gauge.go
- promutils/labeled/stopwatch.go
- promutils/scope.go
_- Make sure to use a concise title for the pull-request._
_- Use #patch, #minor or #major in the pull-request title to bump the corresponding version. Otherwise, the patch version
will be bumped. [More details](https://github.com/marketplace/actions/github-tag-bump)_
_Please replace this text with a description of what this PR accomplishes._
_NA_
OR
> Sanitize metric names before creation

- storage/stow_store.go
- storage/stow_store_test.go
Use storage prefix `abfs://` instead of `afs://`, which is not supported by the azure fsspec plugin, see https://github.com/fsspec/adlfs/blob/bc6e7498af806fe851b4c0157612033b46c03176/README.md
Use storage prefix `abfs://` instead of `afs://`, which is not supported by the azure fsspec plugin, see https://github.com/fsspec/adlfs/blob/bc6e7498af806fe851b4c0157612033b46c03176/README.md
> #patch Fix azure stow storage prefix

- promutils/labeled/counter.go
- promutils/labeled/counter_test.go
- promutils/labeled/gauge.go
- promutils/labeled/gauge_test.go
- promutils/labeled/stopwatch.go
- promutils/labeled/stopwatch_test.go
- promutils/labeled/summary.go
- promutils/labeled/summary_test.go
Signed-off-by: Kevin Su <pingsutw@apache.org>
We should append the labels that don't exist in metricStringKeys
Failed to start datacatalog in single binary because we attempted to register the same metric key.
Error message:
```
Failed to register metrics. Error: descriptor Desc{fqName: \"datacatalog:datacatalog:storage:read_failure\", help: 
\"Indicates failure in GET for a given reference\", constLabels: {}, variableLabels: [app_name project domain exec_id wf 
node task tasktype runtime_type runtime_version failure_type failure_type]} is invalid: duplicate label names [goroutine 83 
[running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 
+0x65\ngithub.com/flyteorg/datacatalog/pkg/rpc/datacatalogservice.NewDataCatalogService.func
```
_How did you fix the bug, …
> Append the labels that don't exist in metricStringKeys

- database/config.go
- logger/config.go
- profutils/server_test.go
Signed-off-by: Katrina Rogan <katroganGH@gmail.com>
It's not really desirable to have a verbose log level as the default. We can configure that for flyte sandbox deployments as necessary.
https://github.com/flyteorg/flyte/issues/2324
_NA_
> Set default log level in config to 'warn'

- .github/workflows/pull_request.yml
- database/gorm.go
Add GetGormLogger to initialize a gorm logger with a specific level and IgnoreRecordNotFoundError flag based on the logger config block.
https://github.com/flyteorg/flyte/issues/2324
_NA_
> Add util to initialize a gorm logger impl from config

- database/gorm.go
Signed-off-by: Katrina Rogan <katroganGH@gmail.com>
By default, setting the gorm log level to 'info' results in all sql being dumped to logs. This is pretty verbose, so this changes settting the gorm log level to 'info' only when the user config is set to 'debug'
https://github.com/flyteorg/flyte/issues/2324
_NA_
> Update gorm 'info' log level translation

- database/config.go
- database/config_test.go
- Decrease the number of max open connection to 100, 1000 is very high number for default
fixes https://github.com/flyteorg/flyte/issues/2171
_NA_
OR
> max open connection in database updated from 1000 to 100

- promutils/labeled/counter.go
- promutils/labeled/counter_test.go
- promutils/labeled/gauge.go
- promutils/labeled/gauge_test.go
- promutils/labeled/stopwatch.go
- promutils/labeled/stopwatch_test.go
- promutils/labeled/summary.go
- promutils/labeled/summary_test.go
This PR computes a unique labels set for each metric on initialization. This is used to popular metric values during increments (so a new slice does not have to be constructed), but more importantly it fixes an issue with corrupting the global metric keys slice.
The Golang `append` function implementation will reuse the underlying slice if it has remaining capacity. In the current implementation, this means that when we construct a new metric with additional labels we may modify the global metricKeys slice. This may result in the corruption of labels within other metrics.
fixes https://github.com/flyteorg/flyte/issues/2597
_NA_
> Set unique labels string on prometheus metrics

- storage/cached_rawstore.go
- storage/cached_rawstore_test.go
- storage/copy_impl.go
- storage/copy_impl_test.go
- storage/init_test.go
- storage/mem_store.go
- storage/mem_store_test.go
- storage/protobuf_store.go
- storage/protobuf_store_test.go
- storage/rawstores.go
- storage/storage.go
- storage/stow_store.go
- storage/stow_store_test.go
Adjust DataStore to allow initialising it multiple times during a single application run.
_NA_
OR
> Extract out data store metrics for re-usability

- storage/protobuf_store_test.go
- storage/rawstores.go
Signed-off-by: iaroslav-ciupin <iaroslav@union.ai>
Fix RefreshConfig by passing old metrics to a new instance.
> Fix RefreshConfig

- storage/cached_rawstore.go
- storage/cached_rawstore_test.go
- storage/mem_store.go
- storage/mem_store_test.go
- storage/storage.go
- storage/stow_store.go
- storage/stow_store_test.go
Flyte storage has been extended to support deletion of stored data.  
`storage.RawStore` now also has a new `Delete` method, removing the referenced data from the underlying store.
`CachedRawStore`, `MemStore` and `StowStore` have been extended to support this new functionality.
This new functionality is required to remove any no longer present `ArtifactData` in datacatalog while [updating artifacts](https://github.com/flyteorg/flyteidl/pull/318).
https://github.com/flyteorg/flyte/issues/2867
_NA_
> Deletion of data from storage

- storage/mocks/composed_protobuf_store.go
- storage/mocks/raw_store.go
- storage/protobuf_store.go
- storage/protobuf_store_test.go
- storage/rawstores.go
NewDefaultProtobufStore was changed to expect `protoMetrics` instead of a `promutils.Scope` in #138. Some of propeller's tests need to instantiate it as well using just a scope.
A few tests in propeller construct a `CompositeDataStore` (and thus a `DefaultProtobufStore`) directly. Since `protoMetrics` and the new `newProtoMetrics` constructor are not exported, the `storage.NewDefaultProtobufStore` constructor can no longer be called.
We could export `newProtoMetrics`, however I've opted to add a contructor "overload" `NewDefaultProtobufStoreWithMetrics` and changed `NewDefaultProtobufStore` to reflect the old signature (accepting a `promutils.Scope`) again.
It also looks like my last PR #140 did not include all generated mocks, so the output of `make generate` was added as well.
_NA_
_NA_
> DefaultProtobufStore constructor accepts scope as well as metrics

- .github/workflows/master.yml
[A previous PR](https://github.com/flyteorg/flytestdlib/pull/133) bumped all go versions to 1.18, but forgot the master workflow. This means that while pull request checks will succeed (with version 1.18) all of the check on merges will fail (go version 1.17) and consequently all releases of this repo have failed since the update. This PR fixes the go version in the master workflow so that merge checks will succeed and a new release can be published.
_NA_
_NA_
> Bump master workflow go versions to 1.18

- .github/workflows/master.yml
- Makefile
Code coverage action is failing. It can be because we're using a [deprecated version of codecov uploader bash](https://github.com/codecov/codecov-bash) script. I removed it and bumped up the version of codecov action to push the coverage report to codecov servers
Refer to [codecov github readme](https://github.com/codecov/codecov-bash#%EF%B8%8F-deprecation-warning-%EF%B8%8F)
_NA_
_NA_
> codecov action version bump

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
This PR allows the github worklow to succeed even if codecov upload fails.
^^^
_NA_
_NA_
> Ignore codecov upload failures

- contextutils/context.go
- contextutils/context_test.go
With the additional of the signal service in FlyteAdmin we may want to track metrics on a per-signal basis. To do this we need to set the signal ID on the context.
^^^
https://github.com/flyteorg/flyte/issues/208
_NA_
> Adding utils for signal ID context

- contextutils/context.go
- contextutils/context_test.go
Add a request ID contextutils fiels.
```golang
ctx = contextutils.WithRequestID(ctx, "request-123")
logger.Infof(ctx, "this happened")
```
`"this happened"` will be tagged with the request id
fixes https://github.com/flyteorg/flyte/issues/3577
> Add a new requestID to Log fields

- config/config_cmd.go
Extend the length of sections produced by the `config docs` subcommand to 120 characters
https://github.com/flyteorg/flyte/pull/3819 is failing due to invalid markdown. This PR increases the length of the section from 80 characters to 120 characters.
_NA_
OR
> Extend length of docs section to 120 characters

- cache/auto_refresh.go
- cache/auto_refresh_example_test.go
- cache/auto_refresh_test.go
- utils/auto_refresh_cache.go
I find that Propeller tries to process the completed task from the `workqueue` because we enqueue the completed item. we should check the item's status before we enqueue them.
Problem:
| Time  | WorkQueue | [Worker](https://github.com/flyteorg/flytestdlib/blob/a8f2b07cd8434b11d9aef9ff7e6d04f7ded4f838/cache/auto_refresh.go#L156-L162) | node Evaluation | 
| ------------- | ------------ |------------- | -----------|
| T1  | Add item1  |                   |      |
| T2  |   |                Process item1  (job finish)       |        |
| T3  | Add item1  |        |         |
| T4  |  |               Process item1  again        |        |
| T5  |  |                       |   Update the node status (running -> succeed)      |
After:
| Time  | WorkQueue | …
> Only enqueue non-terminal tasks
